name: CI

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  checks: write

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo nextest run --profile ci

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: "target/nextest/ci/junit.xml"
          detailed_summary: true
          include_passed: true
